version: '3.9'

services:
  php_apache:
    image: mdobydullah/anyxel-pg-file-upload:1.0
    build:
      context: .
      dockerfile: ./.docker/php-apache.dockerfile
    volumes:
        - ./app:/var/www/html:delegated
    ports:
      - 80:80