version: '3.9'

services:
  app:
    image: anyxel/pg-file-upload:latest
    build:
      context: .
      dockerfile: ./.docker/php-apache.dockerfile
    volumes:
        - ./app:/var/www/html:delegated
    ports:
      - 80:80